import { ArrowDown, ArrowUpRight, Cpu, GitBranch, Layers3, ShieldCheck } from 'lucide-react'
import { ArrowLink, Evidence, Pipeline, SectionLabel, Shell } from '@/components/astraos'
import { RuntimeStatus } from '@/components/runtime-status'
import { SystemStatus } from '@/components/system-status'

export default function Page() {
  return <Shell><section className="grid-texture border-b hairline"><div className="mx-auto grid max-w-7xl gap-16 px-5 pb-20 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pb-28 lg:pt-28"><div><SectionLabel number="00">AI-NATIVE INFRASTRUCTURE INTELLIGENCE</SectionLabel><h1 className="mt-7 max-w-4xl text-balance text-5xl font-medium leading-[1.02] tracking-[-.055em] md:text-7xl">Systems that reason about their <span className="text-accent">future state.</span></h1><p className="mt-7 max-w-xl text-pretty text-base leading-7 text-muted-foreground">AstraOS observes system behavior, models workload state, forecasts infrastructure pressure, generates constrained optimization policies, and verifies outcomes through a continuous feedback loop.</p><div className="mt-9 flex flex-wrap gap-6"><ArrowLink href="/architecture">Explore architecture</ArrowLink><ArrowLink href="/runtime">View runtime</ArrowLink><ArrowLink href="/research">View research</ArrowLink></div><div className="mt-14 flex flex-wrap gap-x-7 gap-y-3 mono text-[10px] tracking-[.1em] text-muted-foreground"><span>OPEN ENGINEERING PROJECT</span><span>AI + SYSTEMS + OBSERVABILITY</span></div></div><div className="self-end border-y hairline py-6"><div className="flex items-center justify-between"><SectionLabel>CONTROL LOOP</SectionLabel><RuntimeStatus /></div><div className="mt-6"><Pipeline compact /></div><p className="mt-5 flex items-center gap-2 mono text-[10px] text-muted-foreground"><span className="size-1.5 bg-accent" /> Each stage is observable, constrained, and verifiable.</p></div></div></section><SystemStatus />
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><SectionLabel number="01">THE PROBLEM</SectionLabel><h2 className="mt-5 max-w-md text-3xl font-medium leading-tight tracking-[-.04em]">Telemetry alone does not create operational intelligence.</h2></div><div><p className="max-w-2xl text-lg leading-8 text-muted-foreground">AstraOS explores the layer after observability: modeling system state, forecasting pressure, choosing a constrained response, and checking whether it helped.</p><div className="mt-12 grid border-y hairline md:grid-cols-2"><div className="border-b hairline p-6 md:border-b-0 md:border-r"><div className="mono text-[10px] text-muted-foreground">OBSERVE</div><div className="mt-4 text-sm">What is happening?</div></div><div className="p-6"><div className="mono text-[10px] text-accent">PREDICT → ACT</div><div className="mt-4 text-sm">What is likely, and what constrained response should occur?</div></div></div></div></div></section>
    <section className="border-y hairline bg-card"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionLabel number="02">EVIDENCE MODEL</SectionLabel><h2 className="mt-5 text-3xl font-medium tracking-[-.04em]">Measured when available. Explicit when not.</h2></div><ArrowLink href="/benchmarks">Benchmark methodology</ArrowLink></div><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Evidence title="RUNTIME APIs" status="AVAILABLE" detail="FastAPI, WebSocket telemetry, and metrics surfaces are wired for a real service." /><Evidence title="ARCHITECTURE" status="IMPLEMENTED" detail="Layered control plane spanning workload, intelligence, policy, and adapters." /><Evidence title="PROOF ENGINE" status="PLANNED" detail="Optimization evidence appears only when a runtime endpoint responds with artifacts." /><Evidence title="BENCHMARKS" status="NOT AVAILABLE" detail="No measured benchmark dataset is attached to this deployment." /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionLabel number="03">WHAT IT EXPLORES</SectionLabel><h2 className="mt-5 max-w-sm text-3xl font-medium leading-tight tracking-[-.04em]">From telemetry to accountable decisions.</h2></div><div className="grid gap-8 sm:grid-cols-2"><Feature icon={<Cpu />} title="Kernel-aware observability" text="Capability-aware process, CPU, memory, thermal, and scheduler signals." /><Feature icon={<Layers3 />} title="AI with a contract" text="Forecasts carry inputs, confidence, and limitations instead of magic claims." /><Feature icon={<GitBranch />} title="Distributed by design" text="Node heartbeat, health scoring, and edge coordination concepts." /><Feature icon={<ShieldCheck />} title="Verification first" text="Policies are evaluated against safety constraints and outcome evidence." /></div></div></section>
  </Shell>
}
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="border-t hairline pt-5"><div className="text-accent [&_svg]:size-5">{icon}</div><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div> }
