import { ArrowLink, CheckList, Evidence, SectionLabel, Shell, Status } from '@/components/astraos'

const layers = [
  ['APPLICATIONS','Workloads, AI jobs, browsers, compilers, services','Process context and demand signals','Runtime requests','workload.py · process_filters.py','ADAPTER-DEPENDENT'],
  ['ASTRAOS RUNTIME','API gateway, event processing, node coordination','Requests and telemetry frames','Normalized runtime state','collector.py · events.py · nodes.py','IMPLEMENTED'],
  ['TELEMETRY','CPU, memory, process, disk, network, thermal streams','procfs, sysfs, WebSocket frames','Features and time-series samples','telemetry.py · metrics.py','EXPERIMENTAL'],
  ['AI INTELLIGENCE','Classification, forecasting, anomaly and root cause models','Features and historical samples','Predictions, scores, explanations','prediction.py · thermal.py · root_cause.py','EXPERIMENTAL'],
  ['POLICY ENGINE','Risk evaluation, constraints, planning and feedback','Intelligence outputs and safety limits','Candidate policies and proof requests','policy.py · healing.py · proof_engine.py','EXPERIMENTAL'],
  ['OPTIMIZATION ENGINE','Simulation, scheduling proposals and verification','Policies plus system capabilities','Actions, recommendations, outcome evidence','optimizer.py · simulator.py','PLANNED'],
  ['eBPF / PERF','Low-level profiling and kernel event adapters','Kernel probes and perf counters','Host-level observability signals','ebpf.py · profiler.py','HOST-DEPENDENT'],
  ['LINUX KERNEL','Scheduling, memory, networking and device interfaces','Hardware interrupts and system calls','Kernel state and capabilities','capability.py · containers.py','HOST-DEPENDENT'],
  ['HARDWARE','CPU, GPU, memory, storage and network devices','Physical resources','Counters, sensors and thermal signals','thermal.py · storage.py','HOST-DEPENDENT'],
]

export function InnerPage({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) { return <Shell><section className="border-b hairline"><div className="mx-auto max-w-7xl px-5 pb-16 pt-20 lg:px-8 lg:pb-24 lg:pt-28"><SectionLabel>{eyebrow}</SectionLabel><h1 className="mt-6 max-w-4xl text-balance text-5xl font-medium leading-[1.03] tracking-[-.055em] md:text-6xl">{title}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground">{intro}</p></div></section>{children}</Shell> }
export function ArchitectureContent() { return <InnerPage eyebrow="SYSTEMS MAP / 01" title="A control layer above the operating system." intro="AstraOS is not an operating system replacement. It is an intelligent runtime that connects observation, model inference, policy generation, and verification to the systems that already run your workloads."><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="relative space-y-2" role="list" aria-label="AstraOS system layers"><div className="mb-6 flex flex-wrap items-center gap-2 mono text-[10px] tracking-[.08em] text-muted-foreground"><span>APPLICATIONS</span><span aria-hidden="true">↓</span><span>CONTROL PLANE</span><span aria-hidden="true">↓</span><span>HOST ADAPTERS</span><span aria-hidden="true">↓</span><span>HARDWARE</span></div>{layers.map(([name,purpose,input,output,modules,status],i)=><div key={name} role="listitem" className="group border hairline bg-card p-5 transition-colors hover:border-accent/60 md:p-7"><div className="grid gap-6 lg:grid-cols-[.55fr_1fr_1fr_1fr_.8fr] lg:items-center"><div><span className="mono text-[10px] text-muted-foreground">LAYER {String(layers.length-i).padStart(2,'0')}</span><h2 className="mt-3 text-lg font-medium">{name}</h2></div><Meta label="PURPOSE" text={purpose} /><Meta label="INPUTS" text={input} /><Meta label="OUTPUTS" text={output} /><div><div className="mono text-[10px] text-muted-foreground">STATUS</div><div className="mt-3"><Status label={status} tone={status === 'IMPLEMENTED' ? 'accent' : 'muted'} /></div><div className="mt-3 mono text-[10px] text-muted-foreground">{modules}</div></div></div></div>)}</div><div className="mt-16 grid gap-4 md:grid-cols-3"><Evidence title="KNOWN LIMITATION" status="HONEST SCOPE" detail="eBPF and thermal capabilities vary by kernel, permissions, and hardware sensors." /><Evidence title="DESIGN PRINCIPLE" status="CONSTRAINTS FIRST" detail="A policy is not an action until safety constraints and verification paths exist." /><Evidence title="DEPLOYMENT MODEL" status="ABOVE LINUX" detail="The underlying OS remains the authority for scheduling and resource control." /></div></div></InnerPage> }
function Meta({label,text}:{label:string;text:string}) { return <div><div className="mono text-[10px] text-muted-foreground">{label}</div><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div> }

export function ResearchContent() { const items=[['01','Predictive Runtime Optimization','Forecasting resource pressure before a threshold becomes an incident.'],['02','Kernel Observability Architecture','A capability-aware path from procfs and sysfs to eBPF and perf adapters.'],['03','Distributed Edge Intelligence','Node heartbeat, health scoring, and coordination under partial connectivity.'],['04','Scheduler Simulation Study','Digital twins for policy evaluation when a live action is unsafe or unavailable.']]; return <InnerPage eyebrow="RESEARCH LIBRARY / 02" title="Engineering questions, not magic claims." intro="AstraOS treats research as an artifact: a question, a method, a runtime, a result, and a boundary around what the result does not prove."><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="grid gap-3 md:grid-cols-2">{items.map(([id,title,text])=><article key={id} className="border hairline bg-card p-7"><span className="mono text-[10px] text-accent">{id} / RESEARCH NOTE</span><h2 className="mt-12 text-xl font-medium tracking-[-.03em]">{title}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{text}</p><div className="mt-8 flex flex-wrap gap-4 mono text-[10px] text-muted-foreground"><span>ABSTRACT</span><span>METHODOLOGY</span><span>LIMITATIONS</span></div></article>)}</div><div className="mt-16 grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><SectionLabel>RESEARCH FORMAT</SectionLabel></div><CheckList items={['Abstract and research question before implementation detail','Experimental setup with environment and number of runs','Results labeled as measured, illustrative, simulation, or unavailable','Artifacts and reproduction steps where the runtime supports them']} /></div></div></InnerPage> }

export function BenchmarksContent({ experiments=false }: { experiments?: boolean }) { const title = experiments ? 'Experiments with a method attached.' : 'Evidence over decoration.'; const eyebrow = experiments ? 'EXPERIMENTS / 03' : 'BENCHMARKS / 04'; const intro = experiments ? 'Each experiment starts with a falsifiable question and ends with an explicit boundary around the evidence. Runtime data is loaded when available; nothing is passed off as production measurement.' : 'A benchmark is useful only when the environment, baseline, workload, metrics, and raw artifacts are visible.'; return <InnerPage eyebrow={eyebrow} title={title} intro={intro}><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="space-y-4"><Experiment id="EXP-001" title="CPU PRESSURE ANALYSIS" question="Can workload-aware policy planning identify sustained CPU pressure before a critical threshold is reached?" /><Experiment id="EXP-002" title="THERMAL TREND FORECAST" question="How does forecast confidence change as telemetry history accumulates on a supported host?" /><Experiment id="EXP-003" title="POLICY VERIFICATION LOOP" question="Can a proposed optimization be evaluated against observed outcome signals without fabricating causality?" /></div></div></InnerPage> }
function Experiment({id,title,question}:{id:string;title:string;question:string}) { return <article className="border hairline bg-card p-6 md:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><span className="mono text-[10px] text-accent">{id}</span><h2 className="mt-3 text-lg font-medium">{title}</h2></div><Status label="AWAITING RUNTIME DATA" /></div><div className="mt-8 grid gap-7 md:grid-cols-2 lg:grid-cols-4"><Meta label="QUESTION" text={question} /><Meta label="ENVIRONMENT" text="Actual host reported by runtime; unavailable until connected." /><Meta label="METRICS" text="CPU utilization · p95 latency · decision latency · lead time" /><Meta label="RESULTS" text="No measured result loaded. Simulation values are not shown as live evidence." /></div><div className="mt-8 border-t hairline pt-5"><div className="flex flex-wrap gap-x-6 gap-y-3 mono text-[10px] text-muted-foreground"><span>BASELINE: REQUIRED</span><span>RUNS: NOT RECORDED</span><span>RAW DATA: UNAVAILABLE</span></div></div></article> }

export function SimpleContent({ kind }: { kind: 'docs'|'about' }) { const docs=kind==='docs'; return <InnerPage eyebrow={docs ? 'DOCUMENTATION / 05' : 'PROJECT / 06'} title={docs ? 'A readable path through the runtime.' : 'Why AstraOS?'} intro={docs ? 'Technical documentation for understanding the control loop, its adapters, and the evidence each endpoint can provide.' : 'Modern systems generate enormous amounts of telemetry, but raw observability does not automatically create intelligent decisions.'}><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="grid gap-16 lg:grid-cols-[.7fr_1.3fr]"><div><SectionLabel>{docs ? 'START HERE' : 'ENGINEERING MOTIVATION'}</SectionLabel><h2 className="mt-5 text-2xl font-medium tracking-[-.03em]">{docs ? 'Understand the system boundary.' : 'Can a runtime reason about what happens next?'}</h2></div><div className="space-y-8 text-sm leading-7 text-muted-foreground">{docs ? <><DocRow title="Runtime API" text="Health, metrics, incidents, root-cause, proof, architecture, and research-report endpoints." /><DocRow title="Event streams" text="WebSocket paths for telemetry, distributed nodes, and runtime events. Connection status is always explicit." /><DocRow title="Adapter capability" text="Host support is not assumed. procfs, sysfs, perf, and eBPF features report what the environment can expose." /></> : <><p>AstraOS explores the question: can a runtime move from observing infrastructure to reasoning about its future state and evaluating optimization policies through continuous feedback?</p><DocRow title="Goals" text="Build an inspectable control layer that links systems engineering, machine intelligence, and measurable evidence." /><DocRow title="Current scope" text="Linux-aware telemetry, FastAPI runtime services, WebSocket streams, forecasting and classification experiments, and proof-oriented UI surfaces." /><DocRow title="Future work" text="More hosts, stronger experiment artifacts, policy execution under explicit permissions, and distributed validation beyond simulation." /></>}</div></div></div></InnerPage> }
function DocRow({title,text}:{title:string;text:string}) { return <div className="border-t hairline pt-5"><h3 className="text-base text-foreground">{title}</h3><p className="mt-2">{text}</p></div> }
